pub mod display_framebuffer { include!("display/framebuffer/driver.rs"); }
pub mod keyboard { include!("input/keyboard/driver.rs"); }
pub mod mouse { include!("input/mouse/driver.rs"); }
pub mod acpi { include!("power/acpi/driver.rs"); }
pub mod ethernet { include!("network/ethernet/driver.rs"); }
pub mod nvme { include!("storage/nvme/driver.rs"); }
pub mod hda { include!("audio/hda/driver.rs"); }
pub mod usb_audio { include!("audio/usb_audio/driver.rs"); }
pub mod framebuffer_memory { include!("display/framebuffer/framebuffer.rs"); }
pub mod gpu { include!("display/gpu/gpu.rs"); }
pub mod gpu_queue { include!("display/gpu/command_queue.rs"); }
pub mod gpu_memory { include!("display/gpu/memory.rs"); }
pub mod touch { include!("input/touch/driver.rs"); }
pub mod gamepad { include!("input/gamepad/driver.rs"); }
pub mod wifi { include!("network/wifi/driver.rs"); }
pub mod bluetooth { include!("network/bluetooth/driver.rs"); }
pub mod battery { include!("power/battery/driver.rs"); }
pub mod cpu_frequency { include!("power/cpu_frequency/driver.rs"); }
pub mod sata { include!("storage/sata/driver.rs"); }
pub mod usb_storage { include!("storage/usb_storage/driver.rs"); }